# Generated by Django 5.1.7 on 2025-03-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
